# Generated by Django 4.0.4 on 2022-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Carros',
        ),
    ]
